name: CI
on: [push, pull_request]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint
